### ISSUE TITLE
Using Data Volumes

### ISSUE THREAD

**Issue by mbalance** [ZencashOfficial/zen-node-docker#1]
I'm trying to setup a zen-node-docker that will use a mounted LV on my Ubuntu 16.04 LTS Server, but it seems not be working like with my ethereum parity docker.

`docker run -d -ti --restart always -v /mnt/zenchain:/mnt/ zencash/zen-node --base-path /mnt/`

I had to stop it again because it's filling my root dir, unlike the parity docker which using the same command.

Any thoughts?

**Comment by mbalance** [comment]
What is the default path?

**Comment by cronicc** [comment]
The container uses two volumes, one for the datadir and one for the zcash-params that are symlinked to ~/.zen and ~/.zcash-params inside the container via [entrypoint.sh](https://github.com/ZencashOfficial/zen-node-docker/blob/master/entrypoint.sh#L25). https://github.com/ZencashOfficial/zen-node-docker/blob/ab6165f70359b024cf355d2498d4535735271882/Dockerfile#L33

So for using host directories the command could look like this:
`docker run -d --restart always -v /mnt/zenchain:/mnt/zen -v /mnt/zcash-params:/mnt/zcash-params -p 9033:9033 zencash/zen-node:v2.0.10`

**Comment by mbalance** [comment]
Okay, so I change it so both will use the zenchain LV that I created.

`docker run -d --restart always -v /mnt/zenchain:/mnt/zen -v /mnt/zenchain:/mnt/zcash-params -p 9033:9033 zencash/zen-node:v2.0.10`

Thanks cronicc! I'm looking forward to running a secure node soon.
