### ISSUE TITLE
Support externalip zen config param as environment variable

### ISSUE THREAD

**Issue by blbradley** [ZencashOfficial/zen-node-docker#12]
New node tracker looks for `externalip` in the zen.conf, but this image does not support it.

**Comment by blbradley** [comment]
Docker Compose doesn't support command substitution. So, my original plan is foiled.

I think this change is still useful. I'll let you know if I still use it with a new plan.

**Comment by cronicc** [comment]
Incorporated it into https://github.com/ZencashOfficial/zen-node-docker/pull/14 with support for multiple external IPs and automatic detection.
