### ISSUE TITLE
reindex howto

### ISSUE THREAD

**Issue by blbradley** [ZencashOfficial/zen-node-docker#7]
Hello!

I'm having trouble figuring out how to reindex using this image. Any ideas?

**Comment by tarrenj** [comment]
You should be able to use `docker exec` to open a shell in the container, then just stop `zend`, and restart it with `--reindex`.  What part are you getting stuck at?

**Comment by blbradley** [comment]
I've tried starting a new container with `zend -reindex` as the CMD with an existing data volume for the datadir. It did not mark the datadir for reindexing.

**Comment by tarrenj** [comment]
> Are you saying you've tried your suggestion?
Yeah.

First, find the container ID:
`docker container ls`

Then, open a shell:
`docker exec -it <container_id> /bin/bash`

After that, you should be able to stop and restart `zend` as you normally would.
